FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements
COPY ingestion_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY src/ ./src/

# Variable de entorno
ENV PYTHONPATH=/app

# Comando por defecto
CMD ["python", "src/ingestion/main.py"]